// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_Commerce_Project.Models;

public partial class Discount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal DiscountPercent { get; set; }

    public byte Active { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();
}