// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_Commerce_Project.Models
{
	public class OrderDetails
	{
		public OrderDetails()
		{
			OrderItems = new HashSet<OrderItems>();
			PaymentDetails = new HashSet<PaymentDetails>();
		}

		public int Id { get; set; }
		public string UserId { get; set; }
		public decimal Total { get; set; }
		public int PaymentId { get; set; }
		public DateTime Created { get; set; }

		public virtual PaymentDetails Payment { get; set; }
		public virtual User User { get; set; }
		public virtual ICollection<OrderItems> OrderItems { get; set; }
		public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
	}
}