// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace E_Commerce_Project.Models;

public partial class User : IdentityUser
{
	public string FirstName { get; set; }

	public string LastName { get; set; }

	public DateTime Created { get; set; }

	public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

	public virtual ICollection<ShoppingSession> ShoppingSession { get; set; } = new List<ShoppingSession>();

	public virtual ICollection<UserAddress> UserAddress { get; set; } = new List<UserAddress>();
}