// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace E_Commerce_Project.Models
{
	public class User : IdentityUser
	{
		public User()
		{
			CartItem = new HashSet<CartItem>();
			OrderDetails = new HashSet<OrderDetails>();
			ShoppingSession = new HashSet<ShoppingSession>();
			UserAddress = new HashSet<UserAddress>();
		}


		public string FirstName { get; set; }
		public string LastName { get; set; }
		public DateTime Created { get; set; }

		public virtual ICollection<CartItem> CartItem { get; set; }
		public virtual ICollection<OrderDetails> OrderDetails { get; set; }
		public virtual ICollection<ShoppingSession> ShoppingSession { get; set; }
		public virtual ICollection<UserAddress> UserAddress { get; set; }
	}
}